/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import Control.AdmFactura;
import Model.Factura;
import com.itextpdf.io.image.ImageData;
import com.itextpdf.io.image.ImageDataFactory;
import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Image;
import com.itextpdf.layout.element.Paragraph;
import java.awt.Font;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author angeldvvp
 */
public class FrmFactura extends javax.swing.JFrame {

    /**
     * Creates new form Factura
     */
    
    public FrmFactura() {
        initComponents();
        TBfactura();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbfac = new javax.swing.JTable();
        btacceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalles Factura"));

        tbfac.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        tbfac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Factura", "Nombres", "Motivo Cita", "Subtotal", "Total", "Archivo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Byte.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbfac);
        if (tbfac.getColumnModel().getColumnCount() > 0) {
            tbfac.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbfac.getColumnModel().getColumn(2).setPreferredWidth(150);
            tbfac.getColumnModel().getColumn(3).setPreferredWidth(20);
            tbfac.getColumnModel().getColumn(4).setPreferredWidth(20);
            tbfac.getColumnModel().getColumn(5).setPreferredWidth(30);
        }

        btacceptar.setText("Aceptar");
        btacceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btacceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(btacceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btacceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Factura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void TBfactura(){
        DefaultTableModel TB = (DefaultTableModel)  tbfac.getModel();
       TB.setRowCount(0);
        AdmFactura aft = new AdmFactura();
        try {
            for(Factura ft :aft.listarFacturas("0946584566")){
                TB.addRow(new Object[]{ft.getCodigoFactura(),ft.getNombres()+" "+ft.getApellidos(),ft.getMotivos(),
                    ft.getSubtotal(),ft.getTotal()});
                int tamaño = tamañofila( tbfac.getFont());
       tbfac.setRowHeight(tamaño);

            }
           TB.fireTableDataChanged();

        } catch (SQLException ex) {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private int tamañofila(Font font) {
        
        int incrementa = 6;
        return font.getSize() + incrementa;
    }
    
    public void factura(Factura dt){
    String DEST = "C:/Users/angeldvvp/Desktop/hola.pdf";
          try{
     PdfDocument pdf = new PdfDocument(new PdfWriter(DEST));
    Document document = new Document(pdf);
    String imagePath = "ruta/a/tu/imagen.jpg";

// Agregar imagen al documento

    String line = "*********Factura********\n";
     String imageFile = "C:/Users/angeldvvp/Desktop/DispensarioMedico/src/main/Imagenes/medicina.jpg"; 
ImageData data = ImageDataFactory.create(imageFile);
Image img = new Image(data); 
img.setWidth(100);
img.setHeight(100);
img.setMarginTop(5);
document.add(img);
    document.add(new Paragraph(line+"Dispensario Mata Sano\n"
    +"Fecha emision: 19/11/2023\n"+"Codigo Factura: "+dt.getCodigoFactura()+"\nNombres y Apellidos del Paciente:"+dt.getNombres()+" "+dt.getApellidos()
    +"\nCedula: "+dt.getCedula()+"\nEdad: 23"+"\nProvincia: "+dt.getProvincia()+"\nCanton: "+dt.getCanton()+
            "\nTelefono: "+dt.getTelefono()+"\nNumero Celular: "+dt.getNumCelular()+"\nNombres y Apellidos del Doctor: "+dt.getApellidoDoc()
    +"\nEspecilidad del medico: "+dt.getEspecialidad()+"\nFecha Visita: 19/11/23 17:00"+"\nMotivo de la cita: "+dt.getMotivos()
    +"\nCosto: $"+dt.getCosto()+"\nDescuento: %"+dt.getDescuento()+"\nIva: %"+dt.getIva()+
            "\nSubtotal: %"+dt.getSubtotal()+"\nTotal: $"+dt.getTotal()+"\n**********GRACIAS POR SU VISITA***** "
    ).setFontSize(12));
     /* document.add(new Paragraph("Dispensario Mata Sano\n"));
      document.add(new Paragraph("Fecha emision: 19/11/2023\n"));
      document.add(new Paragraph("Codigo Factura: "+dt.getCodigoFactura()));
      document.add(new Paragraph("\nNombres y Apellidos del Paciente:"+dt.getNombres()+" "+dt.getApellidos()));
      document.add(new Paragraph("\nCedula: "+dt.getCedula()));
      document.add(new Paragraph("\nEdad: 23"));
      document.add(new Paragraph("\nProvincia: "+dt.getProvincia()));
      document.add(new Paragraph("\nCanton: "+dt.getCanton()));
      document.add(new Paragraph("\nTelefono: "+dt.getTelefono()));
      document.add(new Paragraph("\nNumero Celular: "+dt.getNumCelular()));
      document.add(new Paragraph("\nNombres y Apellidos del Doctor: "+dt.getApellidoDoc()));
      document.add(new Paragraph("\nEspecilidad del medico: "+dt.getEspecialidad()));
       document.add(new Paragraph("\nFecha Visita: 19/11/23 17:00"));
       document.add(new Paragraph("\nMotivo de la cita: "+dt.getMotivos()));
        document.add(new Paragraph("\nCosto: $"+dt.getCosto()));
        document.add(new Paragraph("\nDescuento: %"+dt.getDescuento()));
        document.add(new Paragraph("\nIva: %"+dt.getIva()));
        document.add(new Paragraph("\nSubtotal: %"+dt.getSubtotal()));
        document.add(new Paragraph("\nTotal: $"+dt.getTotal()));
        document.add(new Paragraph("\n**********GRACIAS POR SU VISITA***** "));*/
      
    document.close();

    System.out.println("Awesome PDF just got created.");
          }catch(Exception e){
              System.out.println(e.getMessage());
          }
    }
    
    private void btacceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btacceptarActionPerformed
        // TODO add your handling code here:
       // FrmFactura ft = new FrmFactura();
        AdmFactura ft = new AdmFactura();
        try {
            for(Factura dt : ft.listarFacturas("0946584566")){
                factura(dt);
                System.out.println("paci: "+dt.getApellidos()+" doc: "+dt.getApellidoDoc()+" "+dt.getCosto());
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(FrmFactura.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex.getMessage());
        }
        
        
    }//GEN-LAST:event_btacceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btacceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbfac;
    // End of variables declaration//GEN-END:variables
}
