/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visual;

import Control.AdmCitasMedicas;
import Control.AdmEspecialidad;
import Control.AdmFactura;
import Control.AdmHorariosCitas;
import Control.AdmMotivos;
import Control.AdmPaciente;
import Control.AdmPagos;
import Control.Excepciones;
import Control.Generarfactura;
import Model.Especialidad;
import Model.Factura;
import Model.HorariosCitas;
import Model.Motivos;
import Model.Paciente;
import com.jtattoo.plaf.AbstractLookAndFeel;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author angeldvvp
 */
public class FrmPaciente extends javax.swing.JFrame {

    /**
     * Creates new form FrmPaciente
     */
    boolean update=false;
    AdmPaciente pct = new AdmPaciente();
     DefaultTableModel TB;
     Paciente pc; char genero='M';
    Map<String, String[]> provinciasCantones ;
    Object iddoc,idccita,Doctor,Ubicacion,Horario,Especialidad,Habitacion;int idpaciente=0;
    int idmotivo=0; float Costo=0f;
    public FrmPaciente(Paciente pct) {
        initComponents();
        provincias();
       TB = (DefaultTableModel)  TBHorarios.getModel();
       pc=pct;
        lbmsj.setText("");
 DatosPaciente(pc);
 


 AdmEspecialidad aes = new AdmEspecialidad();
 aes.getEspecialidad(cbespe);
       
 
           txtcedula.setEnabled(false);
                txtnomb.setEnabled(false);
                  txtape.setEnabled(false);
                  txtnumcel.setEnabled(false);
                 txtpanedir.setEnabled(false);
                   txttel.setEnabled(false);
                   cbgenero.setEnabled(false);
                   
               datenc.setEnabled(false);
               
                CBprovincias.setEnabled(false);
                CBCantones.setEnabled(false);
                txtcorreo.setEnabled(false);
            
                
              TBHorarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

      TBHorarios.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    // Obtener la fila seleccionada
                    int selectedRow = TBHorarios.getSelectedRow();

                    // Verificar si hay una fila seleccionada
                    if (selectedRow != -1) {
                        // Obtener los valores de las celdas en la fila seleccionada
                        idccita=TBHorarios.getValueAt(selectedRow, 0);
                        iddoc=TBHorarios.getValueAt(selectedRow, 1);
                          Doctor=TBHorarios.getValueAt(selectedRow, 2);
                          Especialidad=TBHorarios.getValueAt(selectedRow, 3);
                           Horario=TBHorarios.getValueAt(selectedRow, 4);
                          Ubicacion=TBHorarios.getValueAt(selectedRow, 5);
                          Habitacion=TBHorarios.getValueAt(selectedRow, 6);
                     lbmsj.setText(Horario+"/ Doctor: "+Doctor+" /Ubicacion: "+Ubicacion);
                       
                    }
                }
               // lbmsj.setText("");
            }
        });
                
                
                
   paneles.setEnabledAt(1, false);  
paneles.setEnabledAt(2, false);
    }

    private FrmPaciente() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

   
                     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        paneles = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        txtnomb = new javax.swing.JTextField();
        txtape = new javax.swing.JTextField();
        CBprovincias = new javax.swing.JComboBox<>();
        CBCantones = new javax.swing.JComboBox<>();
        txtnumcel = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtpanedir = new javax.swing.JTextPane();
        jLabel16 = new javax.swing.JLabel();
        cbgenero = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        txttel = new javax.swing.JTextArea();
        btenviar = new javax.swing.JButton();
        datenc = new com.toedter.calendar.JDateChooser();
        jp2 = new javax.swing.JPanel();
        btbuscar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TBHorarios = new javax.swing.JTable();
        cbespe = new javax.swing.JComboBox<>();
        cbmt = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        lbmsj = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cbsector = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        btmotv = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        rdpaypal = new javax.swing.JRadioButton();
        rdcredi = new javax.swing.JRadioButton();
        rdtransfer = new javax.swing.JRadioButton();
        btpagar = new javax.swing.JButton();
        rddebi = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtresumen = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btperfil = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        lbnomb = new javax.swing.JLabel();
        bthistorial = new javax.swing.JButton();
        btfacturas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Citas Medicas");
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(80, 20));
        setResizable(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\angeldvvp\\Desktop\\DispensarioMedico\\src\\main\\Imagenes\\Redmedicina.jpg")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 24)); // NOI18N
        jLabel1.setText("Dispensario Medico");

        jLabel2.setFont(new java.awt.Font("Perpetua", 0, 22)); // NOI18N
        jLabel2.setText("Mata Sano");

        paneles.setBackground(new java.awt.Color(204, 204, 255));
        paneles.setBorder(javax.swing.BorderFactory.createTitledBorder("Citas Medicas"));
        paneles.setMinimumSize(new java.awt.Dimension(110, 152));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Editar Informacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombres:");

        jLabel5.setText("Apellidos:");

        jLabel6.setText("Cedula:");

        jLabel7.setText("Fecha de nacimiento:");

        jLabel8.setText("Provincia:");

        jLabel9.setText("Canton:");

        jLabel10.setText("Telefono:");

        jLabel11.setText("Numero de Celular:");

        jLabel12.setText("Direccion:");

        CBprovincias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBprovinciasItemStateChanged(evt);
            }
        });
        CBprovincias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBprovinciasActionPerformed(evt);
            }
        });

        CBCantones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBCantonesActionPerformed(evt);
            }
        });

        jButton4.setText("Siguiente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(txtpanedir);

        jLabel16.setText("Genero:");

        cbgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        cbgenero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbgeneroItemStateChanged(evt);
            }
        });
        cbgenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgeneroActionPerformed(evt);
            }
        });

        jLabel25.setText("Correo Electronico:");

        txttel.setColumns(20);
        txttel.setRows(5);
        jScrollPane5.setViewportView(txttel);

        btenviar.setText("Enviar Cambios");
        btenviar.setEnabled(false);
        btenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btenviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)
                                .addComponent(jLabel10))
                            .addComponent(txtnomb, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(485, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(datenc, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(105, 105, 105)
                                        .addComponent(jLabel16))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtnumcel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbgenero, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(CBCantones, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btenviar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBprovincias, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)
                                .addComponent(jLabel25)
                                .addGap(18, 18, 18)
                                .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtcedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtnomb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(datenc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnumcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(CBprovincias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBCantones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addGap(29, 29, 29))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btenviar))
                .addGap(26, 26, 26))
        );

        paneles.addTab("Verificar Datos", jPanel1);

        jp2.setBackground(new java.awt.Color(255, 255, 255));

        btbuscar.setText("Buscar Disponibilidad");
        btbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuscarActionPerformed(evt);
            }
        });

        jLabel13.setText("Horarios Escogido:");

        jLabel14.setText("Especialidad:");

        jLabel15.setText("Motivo Especifico (Opcional):");

        TBHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDHorario", "IDDoctor", "Doctor", "Especilidad", "Horario", "Direccion", "Habitacion", "Disponibilidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TBHorarios);

        cbespe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja uno...." }));
        cbespe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbespeItemStateChanged(evt);
            }
        });

        cbmt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Motivo Especifico" }));
        cbmt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbmtItemStateChanged(evt);
            }
        });

        jButton5.setText("Confirmar y avanzar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel18.setText("Horarios Disponibles:");

        lbmsj.setText("//////");

        jLabel22.setText("Sector:");

        cbsector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Norte", "Sur" }));
        cbsector.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbsectorItemStateChanged(evt);
            }
        });

        btmotv.setText("?");
        btmotv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmotvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbmsj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(19, 19, 19))
            .addGroup(jp2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbsector, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 299, Short.MAX_VALUE)
                        .addComponent(jLabel24)
                        .addContainerGap(655, Short.MAX_VALUE))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbespe, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btmotv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbmt, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jp2Layout.createSequentialGroup()
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btbuscar))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel18))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(cbsector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(cbespe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(btmotv, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btbuscar)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lbmsj))
                        .addGap(29, 29, 29))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        paneles.addTab("Cita Medica", jp2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel21.setText("Detalles de la Cita Medica:");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Metodo de Pago"));

        buttonGroup1.add(rdpaypal);
        rdpaypal.setText("PayPal");

        buttonGroup1.add(rdcredi);
        rdcredi.setText("Tarjeta de Credito ");
        rdcredi.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdcrediStateChanged(evt);
            }
        });

        buttonGroup1.add(rdtransfer);
        rdtransfer.setText("Transferencia Bancaria");

        btpagar.setText("Realizar Pago");
        btpagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpagarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rddebi);
        rddebi.setText("Tarjeta de Debito");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdpaypal)
                            .addComponent(rdcredi, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rdtransfer)
                            .addComponent(rddebi, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(btpagar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(rdcredi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rddebi)
                .addGap(10, 10, 10)
                .addComponent(rdpaypal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdtransfer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btpagar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        txtresumen.setEditable(false);
        txtresumen.setColumns(20);
        txtresumen.setRows(5);
        jScrollPane1.setViewportView(txtresumen);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(49, 977, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(14, 14, 14))
        );

        paneles.addTab("Detalles", jPanel3);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        btperfil.setBackground(new java.awt.Color(204, 204, 255));
        btperfil.setText("Cerrar Sesion");
        btperfil.setBorder(null);
        btperfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btperfilActionPerformed(evt);
            }
        });

        jLabel17.setText("Usuario:");

        lbnomb.setText("NombUSu");

        bthistorial.setBackground(new java.awt.Color(204, 204, 255));
        bthistorial.setText("Historial Medico");
        bthistorial.setBorder(null);
        bthistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthistorialActionPerformed(evt);
            }
        });

        btfacturas.setBackground(new java.awt.Color(204, 204, 255));
        btfacturas.setText("Facturas");
        btfacturas.setBorder(null);
        btfacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btfacturasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbnomb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bthistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(btperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(899, Short.MAX_VALUE)
                    .addComponent(btfacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(119, 119, 119)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btperfil, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(lbnomb)
                    .addComponent(bthistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btfacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(447, 447, 447)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(92, 92, 92))
                            .addComponent(jLabel1)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(77, 77, 77))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(paneles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneles, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    public void provincias(){
      provinciasCantones = new HashMap<>();

    provinciasCantones.put("Azuay", new String[]{"Cuenca", "Gualaceo", "Paute", "Santa Isabel"});
    provinciasCantones.put("Bolívar", new String[]{"Guaranda", "Caluma", "Chillanes", "Chimbo"});
    provinciasCantones.put("Cañar", new String[]{"Azogues", "Biblián", "Cañar", "La Troncal"});
    provinciasCantones.put("Carchi", new String[]{"Tulcán", "Bolívar", "Espejo", "Mira"});
     provinciasCantones.put("Chimborazo", new String[]{"Riobamba","Alausí","Chambo","Chunchi","Colta","Cumandá","Guamote","Guano","Pallatanga","Penipe"});
     provinciasCantones.put("Cotopaxi", new String[]{"Latacunga","La Maná","Pangua","Pujilí","Salcedo","Saquisilí","Sigchos"});
      provinciasCantones.put("El Oro", new String[]{"Machala","Arenillas","Atahualpa","Balsas","Chilla","El Guabo\n","Huaquillas","Marcabelí","Pasaje","Piñas","Portovelo","Santa Rosa","Zaruma"});
       provinciasCantones.put("Esmeraldas", new String[]{"Esmeraldas","Eloy Alfaro","Muisne","Quinindé","Río Verde","San Lorenzo"});
        provinciasCantones.put("Galápagos", new String[]{"Santa Cruz","San Cristóbal","Isabela"});
         provinciasCantones.put("Carchi", new String[]{"Tulcán", "Bolívar", "Espejo", "Mira"});
      provinciasCantones.put("Guayas", new String[]{"Guayaquil","Alfredo Baquerizo Moreno (Jujan)","Balao","Balzar","Colimes","Coronel Marcelino Maridueña","Daule","Durán","El Empalme","El Triunfo","Milagro","Naranjal","Naranjito","Nobol","Palestina","Pedro Carbo","Playas","Salitre (Urbina Jado)","Samborondón","Santa Lucía","Simón Bolívar","Yaguachi"});
     
     for(String arra:provinciasCantones.keySet()){
       CBprovincias.addItem(arra);
         System.out.println(arra);
     }
   
}
    public void Cantones(){
         String provinciaSeleccionada = (String) CBprovincias.getSelectedItem();

       
        String[] cantones = provinciasCantones.get(provinciaSeleccionada);

        CBCantones.removeAllItems();

        if (cantones != null) {
            for (String canton : cantones) {
                CBCantones.addItem(canton);
            }
        }
    }
   
  
    
    public void DatosPaciente(Paciente pc){
        AdmPaciente pct = new AdmPaciente();
        
        // System.out.println(pc.getIdPaciente()+"id");
        try {
            for (Paciente dt: pct.DatoPaciente(pc.getIdPaciente())) {
                idpaciente=pc.getIdPaciente();
               // System.out.println(pc.getIdPaciente()+"id");
                txtcedula.setText(dt.getCedula());
                txtnomb.setText(dt.getNombres());
                  txtape.setText(dt.getApellidos());
                  txtnumcel.setText(dt.getNumCelular());
                 txtpanedir.setText(dt.getDireccion());
               lbnomb.setText(dt.getNombres()+" "+dt.getApellidos());
                   if(dt.getGenero()=='M'){
                        cbgenero.setSelectedIndex(0);
                   }else{
                        cbgenero.setSelectedIndex(1);
                   }
                   DateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");

            Date fecha = formatoFecha.parse(dt.getFechaNacimiento());

          
               datenc.setDate(fecha);
               
                CBprovincias.setSelectedItem(dt.getProvincia());
                CBCantones.setSelectedItem(dt.getCanton());
                txtcorreo.setText(dt.getCorreoElectronico());
                 
            }
            for (Paciente dt: pct.TelefonPaciente(pc.getIdPaciente())) {
                   txttel.append(dt.getTelefono()+"\n");
                   
                 }
        } catch (SQLException ex) {
            Logger.getLogger(FrmPaciente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(FrmPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
        
    }
    
    public void HorariosCitas(int disponi, String ubi, String espe) throws Excepciones{
        
        
    
        AdmHorariosCitas act = new AdmHorariosCitas();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
try{
    TB.setRowCount(0);
            for (HorariosCitas dt: act.HorariosDispo( disponi,  ubi,  espe)) {
                
               String fecha=formatoFecha.format(dt.getFechaHora());
                TB.addRow(new Object[]{dt.getIdHorario(),dt.getIdMedico(),dt.getDoctor(),dt.getSpecialidad(),fecha,dt.getDireccion(),
                    dt.getArea(),dt.getDisponible()});
            
                 TB.fireTableDataChanged();
                   lbmsj.setText("");
            }
          
                  
        } catch (SQLException ex) {
            Logger.getLogger(FrmPaciente.class.getName()).log(Level.SEVERE, null, ex);
        } catch(Excepciones e){
           lbmsj.setText(e.getMessage());
        }

    
        
    }
    
    
    
    private void btfacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btfacturasActionPerformed
     FrmFactura ft;
         try {
             ft = new FrmFactura(idpaciente);
               ft.setVisible(true);
         } catch (Excepciones ex) {
             Logger.getLogger(FrmPaciente.class.getName()).log(Level.SEVERE, null, ex);
         } catch (SQLException ex) {
             Logger.getLogger(FrmPaciente.class.getName()).log(Level.SEVERE, null, ex);
         }
   
    }//GEN-LAST:event_btfacturasActionPerformed

    private void btmotvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmotvActionPerformed
        JOptionPane.showMessageDialog(null, "Si no desea especificar un motivo especifico se ingresara como un agendado general o consulta/visita comun");
    }//GEN-LAST:event_btmotvActionPerformed

    private void btbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuscarActionPerformed
if(cbsector.getSelectedIndex()==0){
          JOptionPane.showMessageDialog(null, "SELECCIONA EL SECTOR DEL DISPENSARIO");
            
       }else{

        try {
            HorariosCitas(1, cbsector.getSelectedItem().toString(), cbespe.getSelectedItem().toString());
            // TODO add your handling code here:
        } catch (Excepciones ex) {
            Logger.getLogger(FrmPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
        lbmsj.setText("");
}
    }//GEN-LAST:event_btbuscarActionPerformed

    private void cbgeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgeneroActionPerformed
        if(cbgenero.getSelectedIndex()==0){
            genero='M';
        }else{
            genero='F';
        }
    }//GEN-LAST:event_cbgeneroActionPerformed

    private void cbgeneroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbgeneroItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbgeneroItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     JOptionPane.showMessageDialog(null, "Informacion Confirmada");
    paneles.setSelectedIndex(1);
    
paneles.setEnabledAt(0, false);
 paneles.setEnabledAt(1, true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CBCantonesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBCantonesActionPerformed

    }//GEN-LAST:event_CBCantonesActionPerformed

    private void CBprovinciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBprovinciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBprovinciasActionPerformed

    private void CBprovinciasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBprovinciasItemStateChanged
        Cantones();
    }//GEN-LAST:event_CBprovinciasItemStateChanged
public void Resumendatos(){
    
    txtresumen.append("****************RESUMEN DE LA CITA MEDICA****************\n"
            + "IDCITA: "+idccita+"\n"+"IDDOCTOR"+iddoc+"\n"+"NOMBRE DEL DOCTOR: "+
            Doctor+"\nLUGAR DEL DISPENSARIO: "+cbsector.getSelectedItem().toString()+" - "+Ubicacion
            +"\n"+"HORARIO: "+Horario+"\n"+"ESPECIALIDAD: "+Especialidad+"\n"+"HABITACION:"+Habitacion+"\n");
    
    
}
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 JOptionPane.showMessageDialog(null, "Informacion Confirmada");
    paneles.setSelectedIndex(2);
   
   paneles.setEnabledAt(1, false);
     Resumendatos();
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed
int idpago=0;
    private void btpagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpagarActionPerformed
float iva=0.12f,subtotal =Costo*iva, total=subtotal+Costo;
        Generarfactura gf = new Generarfactura();
        AdmHorariosCitas cth = new AdmHorariosCitas();
AdmFactura aft = new AdmFactura();
   if(rddebi.isSelected()){idpago=300;} 
if(rdpaypal.isSelected()){idpago=301;}
if(rdtransfer.isSelected()){idpago=302;}       
        AdmPagos pg = new AdmPagos();
       AdmCitasMedicas ct = new  AdmCitasMedicas();
       
         try {
             System.out.println(idpaciente+" "+ idpago);
             if(pg.ingresarPago(idpaciente, idpago)==true){
                 int horario=(Integer) idccita;
                 int idmedic=(Integer) iddoc;
                   System.out.println(horario+" "+ idmedic);
            ct.IngresarCita(idpaciente, idmedic,horario , idmotivo);
            aft.CrearFactura(idpaciente, idmedic, horario, idmotivo, iva,subtotal ,total,Costo);
            gf.GenerarFactura(idpaciente);
            cth.SetHorariOcupado(horario,2);
         JOptionPane.showMessageDialog(null, "PAGO REALIZADO- CITA MEDICA AGENDADA- FACTURA GENERADA REVISAR SECCION FACTURAS");
            
             }else{
                 System.out.println("error al ingresar");
             }
         } catch (Excepciones ex) {
             Logger.getLogger(FrmPaciente.class.getName()).log(Level.SEVERE, null, ex);
             System.out.println(ex.getMessage()+ex.getStackTrace());
         } catch (SQLException ex) {
             Logger.getLogger(FrmPaciente.class.getName()).log(Level.SEVERE, null, ex);
         }
        
    }//GEN-LAST:event_btpagarActionPerformed

    private void rdcrediStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdcrediStateChanged
       if(rdcredi.isSelected()){
idpago=303;

}
    }//GEN-LAST:event_rdcrediStateChanged
   AdmMotivos mt = new AdmMotivos();
    private void cbmtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbmtItemStateChanged
        Motivos mtt=(Motivos) cbmt.getSelectedItem();
int id = mtt.getId();System.out.println(id+" idmt3");
float costo=mtt.getCosto();
 idmotivo=id; 
 Costo=costo;
    }//GEN-LAST:event_cbmtItemStateChanged

    private void cbespeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbespeItemStateChanged
        Especialidad sp=(Especialidad) cbespe.getSelectedItem();
int id = sp.getId();System.out.println(id+" idmt2");
    
 mt.getmotivos(cbmt,id);
        
        
        
        
    }//GEN-LAST:event_cbespeItemStateChanged

    private void bthistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthistorialActionPerformed
       FrmHistorialMedico fhm;
         try {
             fhm = new FrmHistorialMedico(idpaciente);
              fhm.setVisible(true);
         } catch (SQLException ex) {
             Logger.getLogger(FrmPaciente.class.getName()).log(Level.SEVERE, null, ex);
         }
      
    }//GEN-LAST:event_bthistorialActionPerformed

    private void cbsectorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbsectorItemStateChanged
   
       
    }//GEN-LAST:event_cbsectorItemStateChanged

    private void btperfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btperfilActionPerformed
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "SESION CERRADA");
        Login l = new Login();
        l.setVisible(true);
    }//GEN-LAST:event_btperfilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
         
        txtnomb.setEnabled(true);
                  txtape.setEnabled(true);
                
                 txtpanedir.setEnabled(true);
                 
                   cbgenero.setEnabled(true);
                   
               datenc.setEnabled(true);
               
                CBprovincias.setEnabled(true);
                CBCantones.setEnabled(true);
               
        btenviar.setEnabled(true);
         jButton1.setEnabled(false);
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
private static String convertirDateAString(Date fecha, String formato) {
        DateFormat dateFormat = new SimpleDateFormat(formato);
        return dateFormat.format(fecha);
    }
    private void btenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btenviarActionPerformed
  
        String formato = "dd/MM/yyyy";

        String fechanac = convertirDateAString(datenc.getDate(), formato);
        
        boolean exito=pct.updpaciente( idpaciente,txtnomb.getText(),txtape.getText(),fechanac,CBprovincias.getSelectedItem().toString(),
              txtpanedir.getText(),CBCantones.getSelectedItem().toString(),genero );
    
          if(exito){
              System.out.println(fechanac);
           JOptionPane.showMessageDialog(null, "DATOS ACTUALIZADOS CORRECTAMENTE");
             btenviar.setEnabled(false);
             txtnomb.setEnabled(false);
                  txtape.setEnabled(false);
                
                 txtpanedir.setEnabled(false);
                 
                   cbgenero.setEnabled(false);
                   
               datenc.setEnabled(false);
               
                CBprovincias.setEnabled(false);
                CBCantones.setEnabled(false);
                DatosPaciente( pc);
               jButton1.setEnabled(true);
       }else{
           JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR");
            txtnomb.setEnabled(false);
                  txtape.setEnabled(false);
                
                 txtpanedir.setEnabled(false);
                 
                   cbgenero.setEnabled(false);
                   
               datenc.setEnabled(false);
               
                CBprovincias.setEnabled(false);
                CBCantones.setEnabled(false);
               
       }
        
        
    }//GEN-LAST:event_btenviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
          /* for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {*/
                    javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel" );
                   // break;
               // }
            //}
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBCantones;
    private javax.swing.JComboBox<String> CBprovincias;
    private javax.swing.JTable TBHorarios;
    private javax.swing.JButton btbuscar;
    private javax.swing.JButton btenviar;
    private javax.swing.JButton btfacturas;
    private javax.swing.JButton bthistorial;
    private javax.swing.JButton btmotv;
    private javax.swing.JButton btpagar;
    private javax.swing.JButton btperfil;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbespe;
    private javax.swing.JComboBox<String> cbgenero;
    private javax.swing.JComboBox<String> cbmt;
    private javax.swing.JComboBox<String> cbsector;
    private com.toedter.calendar.JDateChooser datenc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel jp2;
    private javax.swing.JLabel lbmsj;
    private javax.swing.JLabel lbnomb;
    private javax.swing.JTabbedPane paneles;
    private javax.swing.JRadioButton rdcredi;
    private javax.swing.JRadioButton rddebi;
    private javax.swing.JRadioButton rdpaypal;
    private javax.swing.JRadioButton rdtransfer;
    private javax.swing.JTextField txtape;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtnomb;
    private javax.swing.JTextField txtnumcel;
    private javax.swing.JTextPane txtpanedir;
    private javax.swing.JTextArea txtresumen;
    private javax.swing.JTextArea txttel;
    // End of variables declaration//GEN-END:variables
}
